[package]
name = "rp1"
version = "0.1.0"
authors = ["Li Jinpei <leekingp1994@163.com>"]
edition = "2018"

[[bin]]
name = "twice"
path = "src/twice.rs"

[[bin]]
name = "twice_two_files"
path = "src/twice_two_files.rs"
